name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-backend-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ec2-52-66-86-13.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dayforge
            git pull origin main
            docker compose -f docker-compose.prod.yml up --build -d